### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by Emik234** [danhen8/prj-rev-bwfs-tea-cozy#5]
Project name: TeaCozy
Summary Grade: Satisfactory

Great job on the visual design of the site! It matched closely to the original site! Your use of multi-line comments and indentation was a breath of fresh air and very good habit to keep up with

The areas of improvement I would say is to take a look at the issues that were posted regarding the flex-box class calls plus this link to get further info on it https://css-tricks.com/snippets/css/a-guide-to-flexbox/ 

As a further challenge, consider adding a few videos that can be auto played, muted and looped. This will take some extra research but could be a really valuable way to challenge yourself to push past what you’ve already learned. Based on your work here, I think it’s a challenge you’re ready for.

**Comment by danhen8** [comment]
Thank you and I will make those changes.
